### PR TITLE
Add ESLint configs

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
If ESLint worked with transitive dependences, I'd probably have made this a single package instead, but for now I think Lerna might be the best bet. ¯\\\_(ツ)_/¯

I have code ready to point some of our private packages over to these configs.

**Comment by jquense** [comment]
seperate packages to manage handling peer deps of plugins? does the `require.resolve` trick to force the local packages not work for plugins?

**Comment by taion** [comment]
They're separate because ESLint plugins have to be peer dependencies of _my_ package (unlike w/Babel), and I don't want everything to have peer deps on the Flow, React, &c. plugins – but I also don't want those plugins to be unmanaged by npm.

**Comment by jquense** [comment]
this is a great example of a dumb design choice by eslint that they keep doubling down on

**Comment by taion** [comment]
Right, like I said, if ESLint worked with transitive dependencies, this Lerna stuff would be pointless, but I think it's worthwhile as-is.

**Comment by jquense** [comment]
fwiw i don't require the peer dep on my personal config, its not great, but eslint errors clearly. It all depends on what tradeoff you want. This looks fine generally

**Comment by taion** [comment]
These plugins actually have breaking changes though – import from 1.x to 2.x, and also we're using things that were only added in recent minor versions of flowtype.

**Pull request merged**
