### PR TITLE
feat: add typescript comment asserts from dtslint

### PR DESCRIPTION
**Pull request by jquense**
Why does eslint make plugins so difficult! There is (AFAIK) no way to add a custom rule in a config so we need to create a brand new package just for it

### CODE REVIEW

**Comment by taion** [comment]
This is super cool. Are you sure this should be in this repo, though? I don't see anything 4C-specific here.

**Comment by itajaja** [comment]
I am confused. shouldn't this be a static typing definition?

**Comment by itajaja** [comment]
maybe I don't know what this is doing AT ALL

**Comment by jquense** [comment]
@itajaja this is for writing tests for types https://github.com/microsoft/dtslint#write-tests you still get the normal typescript errors

**Comment by jquense** [comment]
@taion true, where would you suggest tho just another repo? seemed fine to have here since the package name is generic

**Comment by itajaja** [comment]
wow, this is cool!

**Comment by taion** [comment]
i was thinking "another repo" to make it easier for other people to send in PRs/&c.

idk. your call

**Comment by jquense** [comment]
https://github.com/4Catalyzer/eslint-plugin-ts-expect

**Pull request closed without merging**
