### PR TITLE
set import/extensions to never

### PR DESCRIPTION
**Pull request by itajaja**
I bumped packages and I got this. I am pretty sure we want it on `never`

### CODE REVIEW

**Comment by itajaja** [comment]
cuplrit seems to be https://github.com/benmosher/eslint-plugin-import/commit/568ca430e3114c582e0ae49509ce294347f6e722#diff-f0697e06e885255448695597a708f517 although I am unclear why

**Comment by taion** [comment]
this is the base: https://github.com/airbnb/javascript/blob/2e3adc98c784be7fa63c7a05271f7aa86c9d6bc7/packages/eslint-config-airbnb-base/rules/imports.js#L139-L143

i think our TS config should just include `.ts` and `.tsx` here

**Comment by taion** [comment]
Why are you turning it off? Just update the upstream rule and add `.ts` and `.tsx`.

**Comment by itajaja** [comment]
good catch. I think that before https://github.com/benmosher/eslint-plugin-import/commit/568ca430e3114c582e0ae49509ce294347f6e722#diff-f0697e06e885255448695597a708f517 the rule with the airbnb value never worked. I actually moved the rule to off and not to simply ignore ts and tsx because it seemed more inline with the other import rules being off. wdyt?

**Comment by taion** [comment]
i think we want this on, though.

the _ordering_-related import rules are off because we have import-sort

**Comment by itajaja** [comment]
alright, done!

**Pull request merged**
