### PR TITLE
fix: Remove no-longer-necessary workaround

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
per the linked issue, apparently this has just worked since at least v7.0.0

**Comment by jquense** [comment]
wait @itajaja _just_ ran into this problem I think? Or maybe that was in the other direction, natively extending a compiled class?

**Comment by itajaja** [comment]
the problem I encountered was extending a class and then compiling only my code, but the original class being kept a class

**Comment by taion** [comment]
right, you can't extend native classes w/transpiled code

**Pull request merged**
