### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by taion**
cc @jquense 

Notable changes from upstream:

Core:
- Trailing commas are required for functions: https://github.com/airbnb/javascript/blob/eslint-config-airbnb-base-v11.2.0/packages/eslint-config-airbnb-base/CHANGELOG.md#1000--2016-11-06
- `import/no-extraneous-dependencies` has exclusions for test and config files where `devDependencies` are allowed: https://github.com/airbnb/javascript/blob/eslint-config-airbnb-base-v11.2.0/packages/eslint-config-airbnb-base/CHANGELOG.md#1100--2016-12-11 (we always overrode this, so this saves effort)
- `no-unused-vars` now ignores rest siblings: https://github.com/airbnb/javascript/blob/eslint-config-airbnb-base-v11.2.0/packages/eslint-config-airbnb-base/CHANGELOG.md#1111--2017-03-03
  - **I'm not sure if we want this**
- `no-param-reassign` has specific excludes for certain named properties, which may be unimportant for us: https://github.com/airbnb/javascript/pull/1325/files

React:
- Disallows using array index as key: https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v15.0.1/packages/eslint-config-airbnb/CHANGELOG.md#1400--2017-01-08
  - I sort of like this... we usually shouldn't do this, and this would be a worthwhile pragma
- Requires non-required props to have a default: https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v15.0.1/packages/eslint-config-airbnb/CHANGELOG.md#1400--2017-01-08
  - This seems silly so I disabled it
- Other new stuff from jsx-a11y? Haven't checked.

### CODE REVIEW

**Comment by itajaja** [comment]
we wouldn't we want `ignoreRestSiblings`? it requires weird hacks otherwise

**Comment by taion** [comment]
Yeah, but it'd also mean that if you legitimately didn't use something, you wouldn't get a lint failure.

**Comment by jquense** [comment]
We should disable trailing function comma's unless we upgrade to node8 which supports them, otherwise we run into annoying issues linting our tooling

**Comment by taion** [comment]
@jquense @chirag04 What are your thoughts on `ignoreRestSiblings`?

**Comment by jquense** [comment]
should we just use Prettier, and pick a lint style that just covers bugs?

**Comment by taion** [comment]
How incompatible is Airbnb code style w/Prettier?

**Comment by jquense** [comment]
its' not particularly. you can use something like `prettier-eslint` tho to cover some of the edge cases.

Generally tho prettier picks "safe" formats, with the exception of removing braces from one line `if`s. The benefit tho is it just handles it all and no one has to worry about it.

**Comment by jquense** [comment]
side point I disagree with the `no-index-key` rule. In 90% of cases things require a key because you are rendering an array, *not* because item order matters. The unique key is only valuable in the latter case.

In relay app land that's not a hard rule to follow since data generally has id's but in libraries its uncommon. I'd vote to keep that rule off, vs littering the code with more pragmas

**Comment by taion** [comment]
I dunno, I think it's generally best practice to find a real identifying key when possible, but I think it's totally fine to have pragmas there. Does it come up a lot? Maybe project-level exclude? I think it's sort of sensible.

I guess the other option questions are `ignoreRestSiblings` on `no-unused` and what to do about trailing function commas.

**Comment by jquense** [comment]
I agree its better, where it feasible to use a real ID, my problem is that for non-app code, 99% of key usage is going to be pragma'd, which is also super annoying to actually write in jsx blocks

**Comment by taion** [comment]
Can you just disable the rule in `.eslintrc` for non-app code? Though shouldn't you be exposing some sort of "key getter" anyway?

**Comment by chirag04** [comment]
imo we shouldn't ignoreRestSiblings. Most likely you will ignore something that you didn't use. I use this pattern very frequently and would prefer to get a warning when having unused rest siblings

**Comment by taion** [comment]
Updated again. Net of the function trailing comma thing, I think this should be good to go.

**Comment by chirag04** [comment]
i think it's fair to force function trailing comma when multiline. this one is not a big deal honestly. i'm fine with either.

**Comment by jquense** [comment]
lgtm

**Pull request merged**
